### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Ruchi61** [arjun-majumdar/CNN_Classifications#1]
hi
i am getting following error on using model
how to solve it
 please guide
ValueError: No gradients provided for any variable: ['conv2d/kernel:0', 'conv2d/bias:0', 'batch_normalization/gamma:0', 'batch_normalization/beta:0', 'conv2d_1/kernel:0', 'conv2d_1/bias:0', 'batch_normalization_1/gamma:0', 'batch_normalization_1/beta:0', 'conv2d_2/kernel:0', 'conv2d_2/bias:0', 'batch_normalization_2/gamma:0', 'batch_normalization_2/beta:0', 'conv2d_3/kernel:0', 'conv2d_3/bias:0', 'batch_normalization_3/gamma:0', 'batch_normalization_3/beta:0', 'conv2d_4/kernel:0', 'conv2d_4/bias:0', 'batch_normalization_4/gamma:0', 'batch_normalization_4/beta:0', 'dense/kernel:0', 'dense/bias:0', 'class_output/kernel:0', 'class_output/bias:0', 'box_output/kernel:0', 'box_output/bias:0'].

**Comment by arjun-majumdar** [comment]
which Jupyter notebook gives this error and for what CNN architecture?

**Comment by arjun-majumdar** [comment]
Closing error due to non-activity and answer.
